# Generated by Django 4.2 on 2023-06-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='base_blog',
            field=models.BooleanField(default=False, verbose_name='Asosiy blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_subcategory',
            field=models.CharField(choices=[('blog', 'Blog'), ('project', 'Loyiha')], default='blog', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.ImageField(default=3, upload_to='images/', verbose_name='Blog post rasmi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Ko'rishlar soni"),
        ),
    ]
