# Generated by Django 4.2 on 2023-06-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_base_blog_blog_blog_subcategory_blog_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_subcategory',
            field=models.CharField(choices=[('blog', 'Blog'), ('project', 'Loyiha')], default='blog', max_length=50, verbose_name='Subkategoriya'),
        ),
    ]
