# Generated by Django 4.2 on 2023-06-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_blog_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(default='Blog haqida', max_length=300, verbose_name='Qisqacha'),
            preserve_default=False,
        ),
    ]
