# Generated by Django 4.2 on 2023-06-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blog_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(default='blog.png', upload_to='images/', verbose_name='Blog post rasmi'),
        ),
    ]
